### ISSUE TITLE
Default value toggle fails /#/environment/localdev2

### ISSUE THREAD

**Issue by prawnsalad** [Vexilla/app#3]
Open an environment, try to set the default value

> Uncaught (in promise) TypeError: Cannot read property 'toggle' of undefined

**Comment by cmgriffing** [comment]
I seem to be having trouble reproducing this locally and in the hosted app.

One thing I tried was removing all localstorage values and then navigating to an environment page. This did not reproduce this issue but it did cause a whole page failure on first render.

Try again in the hosted version of the app or pull down the latest to your local.

Maybe fixed by:
https://github.com/Vexilla/app/commit/34db9142296bc7b7fbd453cf00ee8ee6f325ec53

**Comment by prawnsalad** [comment]
https://github.com/Vexilla/app/commit/34db9142296bc7b7fbd453cf00ee8ee6f325ec53 does indeed fix the issue. Nice!
